CREATE DATABASE mollinger;
USE mollinger;

CREATE TABLE USER_ROLES(
    ID INT NOT NULL AUTO_INCREMENT, 
    Name VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO USER_ROLES (Name) VALUES ('Admin');
INSERT INTO USER_ROLES (Name) VALUES ('Customer');



CREATE TABLE COUNTRIES(
    COUNTRY_ID INT NOT NULL AUTO_INCREMENT, 
    COUNTRY_NAME VARCHAR(25) NOT NULL, 
    PRIMARY KEY(COUNTRY_ID)
);

INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Romania');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('USA');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Luxembourg');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Afghanistan');


CREATE TABLE PPL (
    PERSON_ID INT NOT NULL AUTO_INCREMENT, 
    First_Name VARCHAR(25) NOT NULL, 
    Second_Name VARCHAR(25) NOT NULL,
    Age INT,
    UserName VARCHAR(25) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Nationality INT NOT NULL,
    User_role INT NOT NULL,
    PRIMARY KEY (PERSON_ID),e have been added
    FOREIGN KEY (Nationality) REFERENCES COUNTRIES(COUNTRY_ID),
    FOREIGN KEY (User_role) REFERENCES USER_ROLES(ID)
);